settings:
  src_path: data/raw/deu_Latn/deu_sample_small.jsonl
  index_path: data/preprocessed/deu_sample_small.idx
  dst_path: data/preprocessed/deu_sample_small.pbin

  jq_pattern: .text
  eod_token: <|endoftext|>

  num_cpus: 2
  processing_batch_size: 4
  raw_samples_queue_size: 50
  processed_samples_queue_size: 50

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_hf_tokenizer
  config:
    pretrained_model_name_or_path: gpt2
    padding: false
    truncation: false
